### ISSUE TITLE
panic: dial tcp 127.0.0.1:1025: getsockopt: connection refused

### ISSUE THREAD

**Issue by Gys** [olliecoleman/alloy#3] opened 2017-09-18 16:23 UTC
Hi

Running 'alloy dev' results in a panic. I guess because I need an smtp server running on 127.0.0.1:1025 ? Something to mention in the readme ? Maybe by default disabled to prevent such panics. Or just log a message with the error.

**Comment by rootsongjc** [comment] 2017-09-19 02:22
The same with the first issue https://github.com/olliecoleman/alloy/issues/1
The doc is not complete especially lack of dependency instructions.

**Comment by olliecoleman** [comment] 2017-09-19 13:57
Yes, @rootsongjc  is correct. This is a duplicate of issue #1.
I have updated the README with instructions for creating the required environment variables.

I am working on making the documentation better.

**Closed as completed by olliecoleman** 2017-09-19 13:57 UTC
